/* this code was generated by automated tool,
   should not edit by hand */

export interface TaskService {
    CreateTask(request: Task): Promise<TaskResponse>;
    ReadTask(request: TaskId): Promise<Task>;
    UpdateTask(request: Task): Promise<TaskResponse>;
    DeleteTask(request: TaskId): Promise<TaskResponse>;
}

export interface Task {
    id?: string;
    title?: string;
    description?: string;
    completed?: boolean;
}

export interface TaskId {
    id?: string;
}

export interface TaskResponse {
    success?: boolean;
    message?: string;
}
